version: '3.8'

services:
  ai-textbook-processor:
    build: .
    ports:
      - "8003:8003"  # FastAPI application
      - "8004:8004"  # Tika server
    environment:
      - PYTHONUNBUFFERED=1
      # Add your Azure OpenAI environment variables here
      # - AZURE_OPENAI_API_KEY=your_api_key
      # - AZURE_OPENAI_ENDPOINT=your_endpoint
      # - AZURE_DEPLOYMENT_NAME=your_deployment_name
      # - LANGSMITH_API_KEY=your_langsmith_key
      # - LANGSMITH_PROJECT=your_project_name
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 