---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	comprehensive_validation(comprehensive_validation)
	normalize_content(normalize_content)
	generate_all_content(generate_all_content)
	format_output(format_output)
	__end__([<p>__end__</p>]):::last
	__start__ --> comprehensive_validation;
	comprehensive_validation -. &nbsp;failed&nbsp; .-> __end__;
	comprehensive_validation -. &nbsp;continue&nbsp; .-> normalize_content;
	generate_all_content --> format_output;
	normalize_content --> generate_all_content;
	format_output --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
